name: NuGet Publish on Push

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Remove default NuGet source (v2)
        run: dotnet nuget remove source nuget.org || true

      - name: Add NuGet v3 source explicitly
        run: dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org

      - name: Restore & Build
        run: |
          dotnet restore
          dotnet build Venus/src/Presentation/Web/Client/Venus.Presentation.Client.Core --configuration Release

      - name: Pack all projects
        run: |
          dotnet pack Venus/src/Core/Venus.Core.Domain --configuration Release --output ./nupkg
          dotnet pack Venus/src/Core/Venus.Core.Application --configuration Release --output ./nupkg
          dotnet pack Venus/src/Infrastructure/Venus.Infrastructure.Persistence --configuration Release --output ./nupkg

      - name: Pack
        run: dotnet pack Venus/src/Presentation/Web/Client/Venus.Presentation.Client.Core --configuration Release --output ./nupkg
    
      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.VENUS_PRESENTATION_CLIENT_CORE }} --source https://api.nuget.org/v3/index.json --skip-duplicate
